export const LOCALE_SUCCESS = "LOCALE_SUCCESS";
export const LOCALE_LOADING = "LOCALE_LOADING";
export const LOCALE_FAILURE = "LOCALE_FAILURE";
export const GET_APPLICATION_LOADING = "GET_APPLICATION_LOADING";
export const GET_APPLICATION_SUCCESS = "GET_APPLICATION_SUCCESS";
export const GET_APPLICATION_FAILURE = "GET_APPLICATION_FAILURE";

export const GET_APPLICATION_SUMMARIZED_LOADING =
  "GET_APPLICATION_SUMMARIZED_LOADING";
export const GET_APPLICATION_SUMMARIZED_SUCCESS =
  "GET_APPLICATION_SUMMARIZED_SUCCESS";
export const GET_APPLICATION_SUMMARIZED_FAILURE =
  "GET_APPLICATION_SUMMARIZED_FAILURE";

// export const GET_ROLE_GROUP_APPLICATION_LOADING =
//   'GET_ROLE_GROUP_APPLICATION_LOADING';
// export const GET_ROLE_GROUP_APPLICATION_SUCCESS =
//   'GET_ROLE_GROUP_APPLICATION_SUCCESS';
// export const GET_ROLE_GROUP_APPLICATION_FAILURE =
//   'GET_ROLE_GROUP_APPLICATION_FAILURE';

export const GET_APPLICATIONS_LOADING = "GET_APPLICATIONS_LOADING";
export const GET_APPLICATIONS_SUCCESS = "GET_APPLICATIONS_SUCCESS";
export const GET_APPLICATIONS_FAILURE = "GET_APPLICATIONS_FAILURE";
export const ADD_APPLICATION_LOADING = "ADD_APPLICATION_LOADING";
export const ADD_APPLICATION_SUCCESS = "ADD_APPLICATION_SUCCESS";
export const ADD_APPLICATION_FAILURE = "ADD_APPLICATION_FAILURE";
export const DELETE_APPLICATION_LOADING = "DELETE_APPLICATION_LOADING";
export const DELETE_APPLICATION_SUCCESS = "DELETE_APPLICATION_SUCCESS";
export const DELETE_APPLICATION_FAILURE = "DELETE_APPLICATION_FAILURE";
export const EDIT_APPLICATION_LOADING = "EDIT_APPLICATION_LOADING";
export const EDIT_APPLICATION_SUCCESS = "EDIT_APPLICATION_SUCCESS";
export const EDIT_APPLICATION_FAILURE = "EDIT_APPLICATION_FAILURE";

export const GENERATE_NEW_APP_TOKEN_LOADING = "GENERATE_NEW_APP_TOKEN_LOADING";
export const GENERATE_NEW_APP_TOKEN_SUCCESS = "GENERATE_NEW_APP_TOKEN_SUCCESS";
export const GENERATE_NEW_APP_TOKEN_FAILURE = "GENERATE_NEW_APP_TOKEN_FAILURE";

export const ROLE_GROUP_RESET_CHANGE_PASSWORD_PERIODS_SUCCESS =
  "ROLE_GROUP_RESET_CHANGE_PASSWORD_PERIODS_SUCCESS";
export const ROLE_GROUP_RESET_CHANGE_PASSWORD_PERIODS_LOADING =
  "ROLE_GROUP_RESET_CHANGE_PASSWORD_PERIODS_LOADING";
export const ROLE_GROUP_RESET_CHANGE_PASSWORD_PERIODS_FAILURE =
  "ROLE_GROUP_RESET_CHANGE_PASSWORD_PERIODS_FAILURE";

export const ROLE_GROUP_CHANGE_PASSWORDS_SUCCESS =
  "ROLE_GROUP_CHANGE_PASSWORDS_SUCCESS";
export const ROLE_GROUP_CHANGE_PASSWORDS_LOADING =
  "ROLE_GROUP_CHANGE_PASSWORDS_LOADING";
export const ROLE_GROUP_CHANGE_PASSWORDS_FAILURE =
  "ROLE_GROUP_CHANGE_PASSWORDS_FAILURE";

export const ROLE_RESET_CHANGE_PASSWORD_PERIODS_SUCCESS =
  "ROLE_RESET_CHANGE_PASSWORD_PERIODS_SUCCESS";
export const ROLE_RESET_CHANGE_PASSWORD_PERIODS_LOADING =
  "ROLE_RESET_CHANGE_PASSWORD_PERIODS_LOADING";
export const ROLE_RESET_CHANGE_PASSWORD_PERIODS_FAILURE =
  "ROLE_RESET_CHANGE_PASSWORD_PERIODS_FAILURE";

export const ROLE_CHANGE_PASSWORDS_SUCCESS = "ROLE_CHANGE_PASSWORDS_SUCCESS";
export const ROLE_CHANGE_PASSWORDS_LOADING = "ROLE_CHANGE_PASSWORDS_LOADING";
export const ROLE_CHANGE_PASSWORDS_FAILURE = "ROLE_CHANGE_PASSWORDS_FAILURE";

export const APP_RESET_CHANGE_PASSWORD_PERIODS_SUCCESS =
  "APP_RESET_CHANGE_PASSWORD_PERIODS_SUCCESS";
export const APP_RESET_CHANGE_PASSWORD_PERIODS_LOADING =
  "APP_RESET_CHANGE_PASSWORD_PERIODS_LOADING";
export const APP_RESET_CHANGE_PASSWORD_PERIODS_FAILURE =
  "APP_RESET_CHANGE_PASSWORD_PERIODS_FAILURE";

export const APP_CHANGE_PASSWORDS_SUCCESS = "APP_CHANGE_PASSWORDS_SUCCESS";
export const APP_CHANGE_PASSWORDS_LOADING = "APP_CHANGE_PASSWORDS_LOADING";
export const APP_CHANGE_PASSWORDS_FAILURE = "APP_CHANGE_PASSWORDS_FAILURE";

export const GET_STS_INFO_LOADING = "GET_STS_INFO_LOADING";
export const GET_STS_INFO_SUCCESS = "GET_STS_INFO_SUCCESS";
export const GET_STS_INFO_FAILURE = "GET_STS_INFO_FAILURE";

export const GET_APP_ENTITY_LOADING = "GET_APP_ENTITY_LOADING";
export const GET_APP_ENTITY_SUCCESS = "GET_APP_ENTITY_SUCCESS";
export const GET_APP_ENTITY_FAILURE = "GET_APP_ENTITY_FAILURE";
export const GET_ALL_APP_ENTITY_LOADING = "GET_ALL_APP_ENTITY_LOADING";
export const GET_ALL_APP_ENTITY_SUCCESS = "GET_ALL_APP_ENTITY_SUCCESS";
export const GET_ALL_APP_ENTITY_FAILURE = "GET_ALL_APP_ENTITY_FAILURE";
export const GET_APP_ENTITIES_LOADING = "GET_APP_ENTITIES_LOADING";
export const GET_APP_ENTITIES_SUCCESS = "GET_APP_ENTITIES_SUCCESS";
export const GET_APP_ENTITIES_FAILURE = "GET_APP_ENTITIES_FAILURE";
export const ADD_APP_ENTITY_LOADING = "ADD_APP_ENTITY_LOADING";
export const ADD_APP_ENTITY_SUCCESS = "ADD_APP_ENTITY_SUCCESS";
export const ADD_APP_ENTITY_FAILURE = "ADD_APP_ENTITY_FAILURE";
export const DELETE_APP_ENTITY_LOADING = "DELETE_APP_ENTITY_LOADING";
export const DELETE_APP_ENTITY_SUCCESS = "DELETE_APP_ENTITY_SUCCESS";
export const DELETE_APP_ENTITY_FAILURE = "DELETE_APP_ENTITY_FAILURE";
export const EDIT_APP_ENTITY_LOADING = "EDIT_APP_ENTITY_LOADING";
export const EDIT_APP_ENTITY_SUCCESS = "EDIT_APP_ENTITY_SUCCESS";
export const EDIT_APP_ENTITY_FAILURE = "EDIT_APP_ENTITY_FAILURE";

export const GET_SRV_AUTH_CAT_LOADING = "GET_SRV_AUTH_CAT_LOADING";
export const GET_SRV_AUTH_CAT_SUCCESS = "GET_SRV_AUTH_CAT_SUCCESS";
export const GET_SRV_AUTH_CAT_FAILURE = "GET_SRV_AUTH_CAT_FAILURE";
export const GET_ALL_SRV_AUTH_CAT_LOADING = "GET_ALL_SRV_AUTH_CAT_LOADING";
export const GET_ALL_SRV_AUTH_CAT_SUCCESS = "GET_ALL_SRV_AUTH_CAT_SUCCESS";
export const GET_ALL_SRV_AUTH_CAT_FAILURE = "GET_ALL_SRV_AUTH_CAT_FAILURE";
export const ADD_SRV_AUTH_CAT_LOADING = "ADD_SRV_AUTH_CAT_LOADING";
export const ADD_SRV_AUTH_CAT_SUCCESS = "ADD_SRV_AUTH_CAT_SUCCESS";
export const ADD_SRV_AUTH_CAT_FAILURE = "ADD_SRV_AUTH_CAT_FAILURE";
export const DELETE_SRV_AUTH_CAT_LOADING = "DELETE_SRV_AUTH_CAT_LOADING";
export const DELETE_SRV_AUTH_CAT_SUCCESS = "DELETE_SRV_AUTH_CAT_SUCCESS";
export const DELETE_SRV_AUTH_CAT_FAILURE = "DELETE_SRV_AUTH_CAT_FAILURE";
export const EDIT_SRV_AUTH_CAT_LOADING = "EDIT_SRV_AUTH_CAT_LOADING";
export const EDIT_SRV_AUTH_CAT_SUCCESS = "EDIT_SRV_AUTH_CAT_SUCCESS";
export const EDIT_SRV_AUTH_CAT_FAILURE = "EDIT_SRV_AUTH_CAT_FAILURE";

export const GET_SERVICE_AUTH_LOADING = "GET_SERVICE_AUTH_LOADING";
export const GET_SERVICE_AUTH_SUCCESS = "GET_SERVICE_AUTH_SUCCESS";
export const GET_SERVICE_AUTH_FAILURE = "GET_SERVICE_AUTH_FAILURE";
export const GET_ALL_SERVICE_AUTH_LOADING = "GET_ALL_SERVICE_AUTH_LOADING";
export const GET_ALL_SERVICE_AUTH_SUCCESS = "GET_ALL_SERVICE_AUTH_SUCCESS";
export const GET_ALL_SERVICE_AUTH_FAILURE = "GET_ALL_SERVICE_AUTH_FAILURE";
export const GET_SERVICE_AUTHS_LOADING = "GET_SERVICE_AUTHS_LOADING";
export const GET_SERVICE_AUTHS_SUCCESS = "GET_SERVICE_AUTHS_SUCCESS";
export const GET_SERVICE_AUTHS_FAILURE = "GET_SERVICE_AUTHS_FAILURE";
export const ADD_SERVICE_AUTH_LOADING = "ADD_SERVICE_AUTH_LOADING";
export const ADD_SERVICE_AUTH_SUCCESS = "ADD_SERVICE_AUTH_SUCCESS";
export const ADD_SERVICE_AUTH_FAILURE = "ADD_SERVICE_AUTH_FAILURE";
export const DELETE_SERVICE_AUTH_LOADING = "DELETE_SERVICE_AUTH_LOADING";
export const DELETE_SERVICE_AUTH_SUCCESS = "DELETE_SERVICE_AUTH_SUCCESS";
export const DELETE_SERVICE_AUTH_FAILURE = "DELETE_SERVICE_AUTH_FAILURE";
export const EDIT_SERVICE_AUTH_LOADING = "EDIT_SERVICE_AUTH_LOADING";
export const EDIT_SERVICE_AUTH_SUCCESS = "EDIT_SERVICE_AUTH_SUCCESS";
export const EDIT_SERVICE_AUTH_FAILURE = "EDIT_SERVICE_AUTH_FAILURE";

export const GET_ATTRIBUTE_AUTH_LOADING = "GET_ATTRIBUTE_AUTH_LOADING";
export const GET_ATTRIBUTE_AUTH_SUCCESS = "GET_ATTRIBUTE_AUTH_SUCCESS";
export const GET_ATTRIBUTE_AUTH_FAILURE = "GET_ATTRIBUTE_AUTH_FAILURE";
export const GET_ALL_ATTRIBUTE_AUTH_LOADING = "GET_ALL_ATTRIBUTE_AUTH_LOADING";
export const GET_ALL_ATTRIBUTE_AUTH_SUCCESS = "GET_ALL_ATTRIBUTE_AUTH_SUCCESS";
export const GET_ALL_ATTRIBUTE_AUTH_FAILURE = "GET_ALL_ATTRIBUTE_AUTH_FAILURE";
export const GET_ATTRIBUTE_AUTHS_LOADING = "GET_ATTRIBUTE_AUTHS_LOADING";
export const GET_ATTRIBUTE_AUTHS_SUCCESS = "GET_ATTRIBUTE_AUTHS_SUCCESS";
export const GET_ATTRIBUTE_AUTHS_FAILURE = "GET_ATTRIBUTE_AUTHS_FAILURE";
export const ADD_ATTRIBUTE_AUTH_LOADING = "ADD_ATTRIBUTE_AUTH_LOADING";
export const ADD_ATTRIBUTE_AUTH_SUCCESS = "ADD_ATTRIBUTE_AUTH_SUCCESS";
export const ADD_ATTRIBUTE_AUTH_FAILURE = "ADD_ATTRIBUTE_AUTH_FAILURE";
export const DELETE_ATTRIBUTE_AUTH_LOADING = "DELETE_ATTRIBUTE_AUTH_LOADING";
export const DELETE_ATTRIBUTE_AUTH_SUCCESS = "DELETE_ATTRIBUTE_AUTH_SUCCESS";
export const DELETE_ATTRIBUTE_AUTH_FAILURE = "DELETE_ATTRIBUTE_AUTH_FAILURE";
export const EDIT_ATTRIBUTE_AUTH_LOADING = "EDIT_ATTRIBUTE_AUTH_LOADING";
export const EDIT_ATTRIBUTE_AUTH_SUCCESS = "EDIT_ATTRIBUTE_AUTH_SUCCESS";
export const EDIT_ATTRIBUTE_AUTH_FAILURE = "EDIT_ATTRIBUTE_AUTH_FAILURE";

export const GET_UI_AUTH_LOADING = "GET_UI_AUTH_LOADING";
export const GET_UI_AUTH_SUCCESS = "GET_UI_AUTH_SUCCESS";
export const GET_UI_AUTH_FAILURE = "GET_UI_AUTH_FAILURE";
export const EDIT_UI_AUTH_LOADING = "EDIT_UI_AUTH_LOADING";
export const EDIT_UI_AUTH_SUCCESS = "EDIT_UI_AUTH_SUCCESS";
export const EDIT_UI_AUTH_FAILURE = "EDIT_UI_AUTH_FAILURE";
export const GET_ALL_UI_AUTH_LOADING = "GET_ALL_UI_AUTH_LOADING";
export const GET_ALL_UI_AUTH_SUCCESS = "GET_ALL_UI_AUTH_SUCCESS";
export const GET_ALL_UI_AUTH_FAILURE = "GET_ALL_UI_AUTH_FAILURE";
export const ADD_UI_AUTH_LOADING = "ADD_UI_AUTH_LOADING";
export const ADD_UI_AUTH_SUCCESS = "ADD_UI_AUTH_SUCCESS";
export const ADD_UI_AUTH_FAILURE = "ADD_UI_AUTH_FAILURE";

export const ADD_APP_ENTITY = "ADD_APP_ENTITY";
export const EDIT_APP_ENTITY = "EDIT_APP_ENTITY";
export const DELETE_APP_ENTITY = "DELETE_APP_ENTITY";

export const GET_APP_ROLE_GROUPS_FROM_UM_LOADING =
  "GET_APP_ROLE_GROUPS_FROM_UM_LOADING";
export const GET_APP_ROLE_GROUPS_FROM_UM_SUCCESS =
  "GET_APP_ROLE_GROUPS_FROM_UM_SUCCESS";
export const GET_APP_ROLE_GROUPS_FROM_UM_FAILURE =
  "GET_APP_ROLE_GROUPS_FROM_UM_FAILURE";

export const ADD_ROLE_GROUP_LOADING = "ADD_ROLE_GROUP_LOADING";
export const ADD_ROLE_GROUP_SUCCESS = "ADD_ROLE_GROUP_SUCCESS";
export const ADD_ROLE_GROUP_FAILURE = "ADD_ROLE_GROUP_FAILURE";
export const EDIT_ROLE_GROUP = "EDIT_ROLE_GROUP";
export const DELETE_ROLE_GROUP = "DELETE_ROLE_GROUP";

export const GET_ROLE_GROUP_SUMMARIZED_LOADING =
  "GET_ROLE_GROUP_SUMMARIZED_LOADING";
export const GET_ROLE_GROUP_SUMMARIZED_SUCCESS =
  "GET_ROLE_GROUP_SUMMARIZED_SUCCESS";
export const GET_ROLE_GROUP_SUMMARIZED_FAILURE =
  "GET_ROLE_GROUP_SUMMARIZED_FAILURE";
export const GET_ALL_ROLE_GROUP_SUMMARIZED_LOADING =
  "GET_ALL_ROLE_GROUP_SUMMARIZED_LOADING";
export const GET_ALL_ROLE_GROUP_SUMMARIZED_SUCCESS =
  "GET_ALL_ROLE_GROUP_SUMMARIZED_SUCCESS";
export const GET_ALL_ROLE_GROUP_SUMMARIZED_FAILURE =
  "GET_ALL_ROLE_GROUP_SUMMARIZED_FAILURE";
export const GET_ROLE_GROUP_LOADING = "GET_ROLE_GROUP_LOADING";
export const GET_ROLE_GROUP_SUCCESS = "GET_ROLE_GROUP_SUCCESS";
export const GET_ROLE_GROUP_FAILURE = "GET_ROLE_GROUP_FAILURE";
export const GET_ALL_ROLE_GROUP_LOADING = "GET_ALL_ROLE_GROUP_LOADING";
export const GET_ALL_ROLE_GROUP_SUCCESS = "GET_ALL_ROLE_GROUP_SUCCESS";
export const GET_ALL_ROLE_GROUP_FAILURE = "GET_ALL_ROLE_GROUP_FAILURE";
export const EDIT_ROLE_GROUP_LOADING = "EDIT_ROLE_GROUP_LOADING";
export const EDIT_ROLE_GROUP_SUCCESS = "EDIT_ROLE_GROUP_SUCCESS";
export const EDIT_ROLE_GROUP_FAILURE = "EDIT_ROLE_GROUP_FAILURE";
export const DELETE_ROLE_GROUP_LOADING = "DELETE_ROLE_GROUP_LOADING";
export const DELETE_ROLE_GROUP_SUCCESS = "DELETE_ROLE_GROUP_SUCCESS";
export const DELETE_ROLE_GROUP_FAILURE = "DELETE_ROLE_GROUP_FAILURE";

export const ADD_ROLE = "ADD_ROLE";
export const DELETE_ROLE = "DELETE_ROLE";
export const ADD_ROLE_LOADING = "ADD_ROLE_LOADING";
export const ADD_ROLE_SUCCESS = "ADD_ROLE_SUCCESS";
export const ADD_ROLE_FAILURE = "ADD_ROLE_FAILURE";
export const DELETE_ROLE_LOADING = "DELETE_ROLE_LOADING";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_FAILURE = "DELETE_ROLE_FAILURE";
export const GET_ROLE_LOADING = "GET_ROLE_LOADING";
export const GET_ROLE_SUCCESS = "GET_ROLE_SUCCESS";
export const GET_ROLE_FAILURE = "GET_ROLE_FAILURE";
export const EDIT_ROLE_LOADING = "EDIT_ROLE_LOADING";
export const EDIT_ROLE_SUCCESS = "EDIT_ROLE_SUCCESS";
export const EDIT_ROLE_FAILURE = "EDIT_ROLE_FAILURE";
export const GET_SELF_ROLE_LOADING = "GET_SELF_ROLE_LOADING";
export const GET_SELF_ROLE_SUCCESS = "GET_SELF_ROLE_SUCCESS";
export const GET_SELF_ROLE_FAILURE = "GET_SELF_ROLE_FAILURE";
export const EDIT_UM_ROLE_LOADING = "EDIT_UM_ROLE_LOADING";
export const EDIT_UM_ROLE_SUCCESS = "EDIT_UM_ROLE_SUCCESS";
export const EDIT_UM_ROLE_FAILURE = "EDIT_UM_ROLE_FAILURE ";
export const GET_UM_ROLE_GROUP_ROLES_LOADING =
  "GET_UM_ROLE_GROUP_ROLES_LOADING";
export const GET_UM_ROLE_GROUP_ROLES_SUCCESS =
  "GET_UM_ROLE_GROUP_ROLES_SUCCESS";
export const GET_UM_ROLE_GROUP_ROLES_FAILURE =
  "GET_UM_ROLE_GROUP_ROLES_FAILURE";

export const GET_USER_LOADING = "GET_USER_LOADING";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";
export const GET_ROLE_USERS_LOADING = "GET_ROLE_USERS_LOADING";
export const GET_ROLE_USERS_SUCCESS = "GET_ROLE_USERS_SUCCESS";
export const GET_ROLE_USERS_FAILURE = "GET_ROLE_USERS_FAILURE";
export const GET_ROLE_GROUP_USERS_LOADING = "GET_ROLE_GROUP_USERS_LOADING";
export const GET_ROLE_GROUP_USERS_SUCCESS = "GET_ROLE_GROUP_USERS_SUCCESS";
export const GET_ROLE_GROUP_USERS_FAILURE = "GET_ROLE_GROUP_USERS_FAILURE";

export const GET_USER_EDIT_INFO_LOADING = "GET_USER_EDIT_INFO_LOADING";
export const GET_USER_EDIT_INFO_SUCCESS = "GET_USER_EDIT_INFO_SUCCESS";
export const GET_USER_EDIT_INFO_FAILURE = "GET_USER_EDIT_INFO_FAILURE";

export const GET_ROLE_GROUP_ROLES_LOADING = "GET_ROLE_GROUP_ROLES_LOADING";
export const GET_ROLE_GROUP_ROLES_SUCCESS = "GET_ROLE_GROUP_ROLES_SUCCESS";
export const GET_ROLE_GROUP_ROLES_FAILURE = "GET_ROLE_GROUP_ROLES_FAILURE";

export const REGISTER_USER_LOADING = "REGISTER_USER_LOADING";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
export const DELETE_REGISTERED_USER_LOADING = "DELETE_REGISTERED_USER_LOADING";
export const DELETE_REGISTERED_USER_SUCCESS = "DELETE_REGISTERED_USER_SUCCESS";
export const DELETE_REGISTERED_USER_FAILURE = "DELETE_REGISTERED_USER_FAILURE";
export const EDIT_REGISTERED_USER_LOADING = "EDIT_REGISTERED_USER_LOADING";
export const EDIT_REGISTERED_USER_SUCCESS = "EDIT_REGISTERED_USER_SUCCESS";
export const EDIT_REGISTERED_USER_FAILURE = "EDIT_REGISTERED_USER_FAILURE";

export const OPEN_MESSAGE = "OPEN_MESSAGE";
export const CLOSE_MESSAGE = "CLOSE_MESSAGE";

export const GET_ALL_APPLICATION_ROLE_GROUP_LOADING =
  "GET_ALL_APPLICATION_ROLE_GROUP_LOADING";
export const GET_ALL_APPLICATION_ROLE_GROUP_SUCCESS =
  "GET_ALL_APPLICATION_ROLE_GROUP_SUCCESS";
export const GET_ALL_APPLICATION_ROLE_GROUP_FAILURE =
  "GET_ALL_APPLICATION_ROLE_GROUP_FAILURE";

export const ADD_APPLICATION_TO_PATH = "ADD_APPLICATION_TO_PATH";
export const ADD_ROLE_GROUP_TO_PATH = "ADD_ROLE_GROUP_TO_PATH";
export const ADD_ROLE_TO_PATH = "ADD_ROLE_TO_PATH";
export const ADD_USER_ROLE_GROUP_TO_PATH = "ADD_USER_ROLE_GROUP_TO_PATH";

// ###############################################################################################
// FMS CONSTANT
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_RESET = "LOGIN_RESET";
export const LOGIN_SUCCESS_CHNG_PASS = "LOGIN_SUCCESS_CHNG_PASS";

export const LOGOUT_LOADING = "LOGOUT_LOADING";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const USER_PROFILE_LOADING = "USER_PROFILE_LOADING";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";
export const USER_PROFILE_RESET = "USER_PROFILE_RESET";

export const RULES_FAILURE = "RULES_FAILURE";
export const RULES_LOADING = "RULES_LOADING";
export const RULES_SUCCESS = "RULES_SUCCESS";
export const RULES_RESET = "RULES_RESET";

export const RULE_ACTION_FAILURE = "RULE_ACTION_FAILURE";
export const RULE_ACTION_LOADING = "RULE_ACTION_LOADING";
export const RULE_ACTION_SUCCESS = "RULE_ACTION_SUCCESS";
export const RULE_ACTION_RESET = "RULE_ACTION_RESET";

export const SYSTEM_LITERAL_FAILURE = "SYSTEM_LITERAL_FAILURE";
export const SYSTEM_LITERAL_LOADING = "SYSTEM_LITERAL_LOADING";
export const SYSTEM_LITERAL_SUCCESS = "SYSTEM_LITERAL_SUCCESS";
export const SYSTEM_LITERAL_RESET = "SYSTEM_LITERAL_RESET";

export const BEHAVIOR_ACTION_FAILURE = "BEHAVIOR_ACTION_FAILURE";
export const BEHAVIOR_ACTION_LOADING = "BEHAVIOR_ACTION_LOADING";
export const BEHAVIOR_ACTION_SUCCESS = "BEHAVIOR_ACTION_SUCCESS";
export const BEHAVIOR_ACTION_RESET = "BEHAVIOR_ACTION_RESET";

export const BEHAVIORS_FAILURE = "BEHAVIORS_FAILURE";
export const BEHAVIORS_LOADING = "BEHAVIORS_LOADING";
export const BEHAVIORS_SUCCESS = "BEHAVIORS_SUCCESS";
export const BEHAVIORS_RESET = "BEHAVIORS_RESET";
