export const ErrorType = {
  BUSINESS_ERROR: "BUSINESS_ERROR",
  UNEXPECTED_ERROR: "UNEXPECTED_ERROR",
  UN_AUTHENTICATED: "UN_AUTHENTICATED",
  UN_AUTHORIZED: "UN_AUTHORIZED",
  SERVER_ERROR: "SERVER_ERROR",
  GENERAL_ERROR: "GENERAL_ERROR",
  NONE: "NONE"
};

export const PageType = {
  RAW: "RAW"
};

export const MessageType = {
  INFO: "INFO",
  WARNING: "WARNING",
  ERROR: "ERROR",
  SUCCESS: "SUCCESS"
};

export const Roles = {
  UM_ADMIN: "UM_ADMIN",
  APP_ADMIN: "APPLICATION_ADMIN",
  ROLE_GROUP_ADMIN: "ROLE_GROUP_ADMIN"
};

export const PageStatus = {
  LOADING: "LOADING",
  DATA_FETCHED: "DATA_FETCHED",
  ERROR_OCCURRED: "ERROR_OCCURRED"
};
